project:
  type: website
  output-dir: docs

website:
  title: "Siaa Singh"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
      - href: Free.qmd
        text: Free For All
      - href: Resume.qmd
        text: Resume

