website:
  title: "Siaa Singh"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
      - href: free.qmd
        text: Free For All
      - href: resume.qmd
        text: Resume
